[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/admin/*"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/admin/*"
  to = "/"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200